apiVersion: skaffold/v4beta8
kind: Config
build:
  # artificats section is telling skaffold about the things that it needs to maintain, means the pods running inside the cluster it needs to track changes.
  artifacts:
    - image: shanbiswas/ticketing-app-auth  # if any changes is done outside src/ folder then it is going to rebuild the image and update the deployment tied to it
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: # if any changes is done inside src/ folder, and it is a .js file, then it is going to push the changes in the pod immediately
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: shanbiswas/ticketing-app-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.js'
    - image: shanbiswas/ticketing-app-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: shanbiswas/ticketing-app-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: shanbiswas/ticketing-app-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: shanbiswas/ticketing-app-payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
  local:  # this is telling not to push the images to docker hub when a change is done, this is not req when using skaffold
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-410104
manifests:
  rawYaml:
    - ./infra/k8s/*