apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - name: tickets
        image: shanbiswas/ticketing-app-tickets #us.gcr.io/ticketing-dev-410104/tickets
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name    # this will give unique client id
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLUSTER_ID
            value: 'ticketing'
          - name: MONGO_URI
            value: 'mongodb://tickets-mongo-srv:27017/ticketing-tickets'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        # ports:
        # - containerPort: <Port>
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
  - name: tickets
    protocol: TCP
    port: 3000
    targetPort: 3000
